
// FRUSTUM CALCULATOR

/*	========================
     Input/Output Variables
    =======================*/

var input.diameter1 = 2;
var input.diameter2 = 4;
var input.lateral = 3;

var output.radius1 = null;
var output.radius2 = null;
var output.angle - null;

/*	=======================
 		Event Listeners
 	======================*/




/*	=======================
         Frustum Math
	======================*/

